/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/C4YlPWcGWZP
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { NavigationMenuLink, NavigationMenuItem, NavigationMenuList, NavigationMenu } from "@/components/ui/navigation-menu"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Card } from "@/components/ui/card"

export function Layout() {
  return (
    <>
      <header className="w-full bg-gray-900 text-white py-12 md:py-20 lg:py-24">
        <div className="container px-4 md:px-6">
          <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">John Doe</h1>
                <p className="max-w-[600px] text-gray-300 md:text-xl">Game Graphic Designer</p>
                <p className="max-w-[600px] text-gray-400 md:text-xl">
                  With over 10 years of experience in the gaming industry, I specialize in creating stunning visuals and
                  UI designs that captivate players and elevate the gaming experience.
                </p>
              </div>
            </div>
            <img
              alt="Hero"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
              height="550"
              src="/placeholder.svg"
              width="550"
            />
          </div>
        </div>
      </header>
      <nav className="w-full bg-gray-100 dark:bg-gray-800 py-4">
        <div className="container px-4 md:px-6">
          <NavigationMenu>
            <NavigationMenuList>
              <NavigationMenuItem>
                <NavigationMenuLink className="group" href="#about">
                  About
                </NavigationMenuLink>
              </NavigationMenuItem>
              <NavigationMenuItem>
                <NavigationMenuLink className="group" href="#portfolio">
                  Portfolio
                </NavigationMenuLink>
              </NavigationMenuItem>
              <NavigationMenuItem>
                <NavigationMenuLink className="group" href="#services">
                  Services
                </NavigationMenuLink>
              </NavigationMenuItem>
              <NavigationMenuItem>
                <NavigationMenuLink className="group" href="#contact">
                  Contact
                </NavigationMenuLink>
              </NavigationMenuItem>
            </NavigationMenuList>
          </NavigationMenu>
        </div>
      </nav>
      <main>
        <section className="w-full py-12 md:py-24 lg:py-32" id="about">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <img
                alt="About"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
                height="550"
                src="/placeholder.svg"
                width="550"
              />
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">About Me</h2>
                  <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                    I am a passionate game graphic designer with a keen eye for detail and a deep understanding of the
                    gaming industry. My work has been featured in numerous award-winning games, and I take pride in
                    creating visuals that captivate and engage players.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800" id="portfolio">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">My Portfolio</h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Explore a selection of my best game art and UI designs that showcase my creativity and technical
                  expertise.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl grid-cols-1 gap-6 py-12 sm:grid-cols-2 lg:grid-cols-3 lg:gap-12">
              <div className="group relative overflow-hidden rounded-xl">
                <img
                  alt="Project 1"
                  className="aspect-video w-full object-cover transition-all duration-300 group-hover:scale-105"
                  height="310"
                  src="/placeholder.svg"
                  width="550"
                />
                <div className="absolute inset-0 bg-gray-900/80 p-4 transition-all duration-300 group-hover:bg-gray-900/60">
                  <div className="flex h-full flex-col justify-end space-y-2">
                    <h3 className="text-xl font-bold text-white">Project 1</h3>
                    <p className="text-gray-300">
                      A detailed UI design for a mobile game featuring a unique art style.
                    </p>
                  </div>
                </div>
              </div>
              <div className="group relative overflow-hidden rounded-xl">
                <img
                  alt="Project 2"
                  className="aspect-video w-full object-cover transition-all duration-300 group-hover:scale-105"
                  height="310"
                  src="/placeholder.svg"
                  width="550"
                />
                <div className="absolute inset-0 bg-gray-900/80 p-4 transition-all duration-300 group-hover:bg-gray-900/60">
                  <div className="flex h-full flex-col justify-end space-y-2">
                    <h3 className="text-xl font-bold text-white">Project 2</h3>
                    <p className="text-gray-300">A set of character illustrations for a fantasy-themed RPG game.</p>
                  </div>
                </div>
              </div>
              <div className="group relative overflow-hidden rounded-xl">
                <img
                  alt="Project 3"
                  className="aspect-video w-full object-cover transition-all duration-300 group-hover:scale-105"
                  height="310"
                  src="/placeholder.svg"
                  width="550"
                />
                <div className="absolute inset-0 bg-gray-900/80 p-4 transition-all duration-300 group-hover:bg-gray-900/60">
                  <div className="flex h-full flex-col justify-end space-y-2">
                    <h3 className="text-xl font-bold text-white">Project 3</h3>
                    <p className="text-gray-300">A user interface design for a multiplayer online battle arena game.</p>
                  </div>
                </div>
              </div>
              <div className="group relative overflow-hidden rounded-xl">
                <img
                  alt="Project 4"
                  className="aspect-video w-full object-cover transition-all duration-300 group-hover:scale-105"
                  height="310"
                  src="/placeholder.svg"
                  width="550"
                />
                <div className="absolute inset-0 bg-gray-900/80 p-4 transition-all duration-300 group-hover:bg-gray-900/60">
                  <div className="flex h-full flex-col justify-end space-y-2">
                    <h3 className="text-xl font-bold text-white">Project 4</h3>
                    <p className="text-gray-300">A series of character designs for a 2D platformer game.</p>
                  </div>
                </div>
              </div>
              <div className="group relative overflow-hidden rounded-xl">
                <img
                  alt="Project 5"
                  className="aspect-video w-full object-cover transition-all duration-300 group-hover:scale-105"
                  height="310"
                  src="/placeholder.svg"
                  width="550"
                />
                <div className="absolute inset-0 bg-gray-900/80 p-4 transition-all duration-300 group-hover:bg-gray-900/60">
                  <div className="flex h-full flex-col justify-end space-y-2">
                    <h3 className="text-xl font-bold text-white">Project 5</h3>
                    <p className="text-gray-300">
                      A user interface concept for a mobile game featuring a minimalist design.
                    </p>
                  </div>
                </div>
              </div>
              <div className="group relative overflow-hidden rounded-xl">
                <img
                  alt="Project 6"
                  className="aspect-video w-full object-cover transition-all duration-300 group-hover:scale-105"
                  height="310"
                  src="/placeholder.svg"
                  width="550"
                />
                <div className="absolute inset-0 bg-gray-900/80 p-4 transition-all duration-300 group-hover:bg-gray-900/60">
                  <div className="flex h-full flex-col justify-end space-y-2">
                    <h3 className="text-xl font-bold text-white">Project 6</h3>
                    <p className="text-gray-300">A set of environmental illustrations for a 3D adventure game.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32" id="services">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">My Services</h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  I offer a wide range of services to help bring your game's visuals to life. From character design to
                  UI development, I'm here to make your project a success.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl grid-cols-1 gap-6 py-12 sm:grid-cols-2 lg:grid-cols-3 lg:gap-12">
              <div className="rounded-xl bg-gray-100 p-6 dark:bg-gray-800">
                <div className="flex h-full flex-col justify-between space-y-4">
                  <div>
                    <h3 className="text-xl font-bold">Character Design</h3>
                    <p className="text-gray-500 dark:text-gray-400">
                      Bring your game's characters to life with unique and memorable designs.
                    </p>
                  </div>
                  <Button className="justify-start" variant="link">
                    Learn More
                  </Button>
                </div>
              </div>
              <div className="rounded-xl bg-gray-100 p-6 dark:bg-gray-800">
                <div className="flex h-full flex-col justify-between space-y-4">
                  <div>
                    <h3 className="text-xl font-bold">UI/UX Design</h3>
                    <p className="text-gray-500 dark:text-gray-400">
                      Craft intuitive and visually appealing user interfaces that enhance the player experience.
                    </p>
                  </div>
                  <Button className="justify-start" variant="link">
                    Learn More
                  </Button>
                </div>
              </div>
              <div className="rounded-xl bg-gray-100 p-6 dark:bg-gray-800">
                <div className="flex h-full flex-col justify-between space-y-4">
                  <div>
                    <h3 className="text-xl font-bold">Environment Design</h3>
                    <p className="text-gray-500 dark:text-gray-400">
                      Create immersive and visually stunning game environments that captivate players.
                    </p>
                  </div>
                  <Button className="justify-start" variant="link">
                    Learn More
                  </Button>
                </div>
              </div>
              <div className="rounded-xl bg-gray-100 p-6 dark:bg-gray-800">
                <div className="flex h-full flex-col justify-between space-y-4">
                  <div>
                    <h3 className="text-xl font-bold">Animation</h3>
                    <p className="text-gray-500 dark:text-gray-400">
                      Bring your game's visuals to life with fluid and dynamic animations.
                    </p>
                  </div>
                  <Button className="justify-start" variant="link">
                    Learn More
                  </Button>
                </div>
              </div>
              <div className="rounded-xl bg-gray-100 p-6 dark:bg-gray-800">
                <div className="flex h-full flex-col justify-between space-y-4">
                  <div>
                    <h3 className="text-xl font-bold">Concept Art</h3>
                    <p className="text-gray-500 dark:text-gray-400">
                      Develop captivating concept art to guide the visual direction of your game.
                    </p>
                  </div>
                  <Button className="justify-start" variant="link">
                    Learn More
                  </Button>
                </div>
              </div>
              <div className="rounded-xl bg-gray-100 p-6 dark:bg-gray-800">
                <div className="flex h-full flex-col justify-between space-y-4">
                  <div>
                    <h3 className="text-xl font-bold">Branding</h3>
                    <p className="text-gray-500 dark:text-gray-400">
                      Develop a cohesive brand identity for your game that resonates with players.
                    </p>
                  </div>
                  <Button className="justify-start" variant="link">
                    Learn More
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t" id="contact">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Get in Touch</h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Have a project in mind? Let's discuss how I can help bring your game's visuals to life.
                </p>
              </div>
              <div className="mx-auto w-full max-w-md space-y-4">
                <form className="grid gap-4">
                  <div className="grid gap-2">
                    <Label htmlFor="name">Name</Label>
                    <Input id="name" required type="text" />
                  </div>
                </form>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
